# Generated by Django 5.2.3 on 2025-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_city_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_id',
            field=models.IntegerField(verbose_name='телеграм id'),
        ),
    ]
